[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
#basic = "DSX41g54wAid4HzHuGt71M7YiCsoqJ7NMBXa8G9cbsLf"
basic = "ymNCSzK5qLoa8NqspphBLbKKLEdbRLzvNsQKnquYuHq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/franck/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
